import Head from "next/head";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { Ellipse } from "./components/Ellipse";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Luminr.co",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const ellipses = [];

  for (let i = 0; i < 8; i++) {
    const top = 30 + i * 1000;
    const isOdd = i % 2 === 0;
    ellipses.push(<Ellipse key={i} top={top} isOdd={isOdd} />);
  }

  return (
    <html lang="en">
      <body className={`${montserrat.className} noise  relative  `}>
        {ellipses}
        {children}
      </body>
    </html>
  );
}
